#!/bin/sh

#
# Build a root certificate
#
source /usr/share/openvpn/easy-rsa/2.0/vars
export KEY_CN=ca
export KEY_NAME=ca

if test $KEY_DIR; then
    cd $KEY_DIR && \
    openssl req -days 3650 -nodes -new -x509 -keyout ca.key -out ca.crt -config $KEY_CONFIG && \
        chmod 0600 ca.key
else
    echo you must define KEY_DIR
fi
