#!/bin/sh

#
# Make a certificate/private key pair using a locally generated
# root certificate.
#

if test $# -ne 1; then
        echo "usage: build-key <name>";
        exit 1
fi

source /usr/share/openvpn/easy-rsa/2.0/vars
export KEY_CN=$1
export KEY_NAME=$1

if test $KEY_DIR; then
    cd $KEY_DIR && \
    openssl req -batch -days 3650 -nodes -new -keyout $1.key -out $1.csr -config $KEY_CONFIG && \
    openssl ca -batch -days 3650 -out $1.crt -in $1.csr -config $KEY_CONFIG && \
    chmod 0600 $1.key
else
    echo you must define KEY_DIR
fi
