#!/bin/sh

#
# Revoke a user certificate
#
source /usr/share/openvpn/easy-rsa/2.0/vars
export KEY_CN=ca
export KEY_NAME=ca

if test $# -ne 1; then
        echo "usage: revoke-user <name>";
        exit 1
fi

if test $KEY_DIR; then
    cd $KEY_DIR && \
    openssl ca -revoke $1.crt -config $KEY_CONFIG && \
    openssl ca -gencrl -out ca.crl -config $KEY_CONFIG && \
    chmod 0644 ca.crl
else
    echo you must define KEY_DIR
fi
